apiVersion: v1
kind: Secret
metadata:
  name: markethub-secrets
  namespace: markethub
type: Opaque
stringData:
  MONGO_PASSWORD: "markethub"
  POSTGRES_ORDER_PASSWORD: "markethub"
  POSTGRES_PAYMENT_PASSWORD: "markethub"
  RABBITMQ_PASSWORD: "markethub"
  KEYCLOAK_DB_PASSWORD: "keycloak"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  STRIPE_SECRET_KEY: "sk_test_placeholder"
  STRIPE_WEBHOOK_SECRET: "whsec_placeholder"
  RESEND_API_KEY: "re_placeholder"
  GRAFANA_ADMIN_PASSWORD: "admin"
  # NextAuth
  AUTH_SECRET: "change-me-in-production"
